#cloud-config
repo_update: true
ntp:
enabled: true
ntp_client: chrony
packages:
  - python3
user: szymon
users:
  - name: szymon
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: root
    ssh_authorized_keys:
    - ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBB>


#1st line 'cloud-config' is necessary
#Don't add '---' on the beginning because it won't apply 'ssh szymon@ip_address' then. You'll still have make 'ssh ubuntu!ip_addres'