apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: szymanel/app:latest
        imagePullPolicy: IfNotPresent
        command: ["uvicorn", "main:app", "--host", "0.0.0.0"]
        # resources:
        #     limits:
        #       memory: "1024Mi"
        #       cpu: "2000m"
        ports:
        - containerPort: 5432
        # volumes:
        # - ${PWD}/nginx.conf:/etc/nginx/nginx.confa
        envFrom:
          - configMapRef:
              name: postgres-config
      #   volumeMounts:
      #     - mountPath: ${PWD}/app-postgres:/var/lib/postgresql/data
      #       name: postgredb
        # volumes:
        #  - name: postgredb
        #    persistentVolumeClaim:
        #     claimName: postgres-pv-claim
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  type: NodePort
  selector:
    app: app
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30080