apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
   matchLabels:
    app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
          - containerPort: 5432
          envFrom:
            - configMapRef:
                name: postgres-config
---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: postgres-config 
      labels:
        app: postgres
    data:
      POSTGRES_DB: fastapi_database
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
---
    apiVersion: v1
    kind: Service
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
       ports:
        - name: postgres
          protocol: TCP
          port: 5432
          targetPort: 5432
       type: NodePort
       selector:
        app: postgres