apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: szymanel/app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        envFrom:
          - configMapRef:
              name: webapp-config
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec:
  ports:
    - name: webapp
      protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080  
  type: NodePort
  selector:
    app: app