---
- hosts: all
  name: play1
  become: true
  become_method: sudo
  tasks:
    - name: Check for Python
      raw: test -e /usr/bin/python
      changed_when: false
      failed_when: false
      register: check_python
  #  - name: Install Python
  #    raw: apt update && apt install python3-minimal
  #    when: check_python.rc != 0

    # - name: AWSCLI
    #   ansible.builtin.shell: python3 -m pip install awscli
    #   become: true

    #  - name: python-docker
    #    ansible.builtin.shell: sudo yum install python-pip
    #    become: true

    # - name: install git
    #   ansible.builtin.shell: sudo yum install git -y
    #   become: true


    - name: Clone A Github Repository With Ansible
      git:
        repo: https://github.com/szymoninetum/simple_app.git
        dest: FastApi
        clone: yes
        update: yes
        force: yes
      become: true

    #Change line with nginx volume in docker-compose.yml file 
    - name: change Docker-Compose file
      shell:
        cp FastApi/docker-compose_host_machine/docker-compose.yml FastApi/


    # - name: Install Docker SDK for Python
    #   pip:
    #     name: "docker<5"
    #   become: true


    - name: Install aptitude
      apt:
        name: aptitude
        state: latest
        update_cache: true

# Installation basic packages
    - name: Install required system packages
      apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true

#Docker installation
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    #Docker-compose installation
    - name: install compose
      become: true
      pip:
        name: docker-compose

    - name: Build image
      shell: echo "PATH=$PATH:/tmp/app" > docker build -t szymanel/app .

    - name: deploy Docker Compose down
      docker_compose:
        project_src: FastApi/
        files:
        - docker-compose.yml
        state: absent
      become: true
      # vars:
      #   ansible_python_interpreter: /bin/python3

    - name: deploy Docker Compose Up
      docker_compose:
        project_src: FastApi/
        files:
        - docker-compose.yml
        state: present
      become: true


#K8s


      # vars:
      #   ansible_python_interpreter: /bin/python3

    #    docker_compose:
    #      project_name: project
    #      definition:
    #       version: "latest"
    #       services:
    #         app:
    #           build: "/tmp/app/"
    #  - name: python-docker
    #    pip:
    #       pip install docker
    #    become: true



  #building image
    #  - name: docker image
    #    copy:
    #      src: ansible_app/simple_app
    #      dest: tmp/
    #      remote_src: yes

    #  - name: DC
    #    shell: echo "PATH=$PATH:/tmp/app" > docker-compose down && docker-compose up

  #docker-compose
    #  - name: test
    #    community.general.docker_compose:
    #      project_src: tmp/
    #      state: present
